import { PrismaClient } from '@prisma/client'

type AuditEntry = {
  action: string
  caseId?: string | null
  userId?: string | null  // Changed from actorId to match schema
  diff?: any              // Changed from data to match schema
}

export async function logAudit(prisma: PrismaClient, e: AuditEntry) {
  try {
    await prisma.auditLog.create({
      data: {
        action: e.action,
        caseId: e.caseId ?? null,
        userId: e.userId ?? null,     // Using correct field name
        diff: e.diff ?? null,         // Using correct field name
        // createdAt will be auto-generated by @default(now())
      },
    })
  } catch (err) {
    console.warn('auditLog create failed (non-fatal):', err)
  }
}
